name: CI Pipeline with Security Tests and Local Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-test:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd src
          npm install

      - name: Start Application
        run: |
          cd src
          nohup npm start &

      - name: Wait for Application to Start
        run: |
          for i in {1..30}; do
            curl -s http://localhost:3000/ && break || sleep 5
          done

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-J report.json -w report.md -r report.html -x report.xml'

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          path: report*

      - name: Call Orchestron API
        run: |
          curl \
          -H "Secret-Key: ${{ secrets.ORCHESTRION_ACCESS_KEY }}" \
          -H "Access-Key: ${{ secrets.ORCHESTRION_SECRET_KEY }}" \
          -v -F file=@report.xml \
          "${{ secrets.ORCHESTRON_URL }}"
